services:
  - type: worker
    name: bot-telegram-tarea3
    runtime: docker
    plan: free
    rootDir: Tarea3
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ZONA_HORARIA
        value: America/Guatemala
      - key: LOG_LEVEL
        value: INFO
